-- STEP 05 : JOIN

-- 01. 없어진 기록 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID;

-- 02. 있었는데요 없었습니다
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID AND O.DATETIME < I.DATETIME
ORDER BY I.DATETIME;

-- 03. 오랜 기간 보호한 동물(1)
-- Oracle
SELECT NAME, DATETIME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) I
WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS) AND ROWNUM <= 3;

-- MySQL
SELECT NAME, DATETIME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) I
WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
LIMIT 3;

-- 04. 보호소에서 중성화한 동물
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID 
AND REGEXP_LIKE(I.SEX_UPON_INTAKE, 'Intact') 
AND REGEXP_LIKE(O.SEX_UPON_OUTCOME, 'Spayed|Neutered') 
ORDER BY I.ANIMAL_ID;