-- STEP 06 : String, Date

-- 01. 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE REGEXP_LIKE(NAME, 'Lucy|Ella|Pickle|Rogan|Sabrina|Mitty')
ORDER BY ANIMAL_ID;

-- 또는
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;


-- 02. 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE REGEXP_LIKE(NAME, 'EL', 'i')
AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME;

-- 03. 중성화 여부 파악하기 -- 꽤 어려웠음 replace를 두번 하면 됨
SELECT ANIMAL_ID, NAME, REGEXP_REPLACE(
    REGEXP_REPLACE(SEX_UPON_INTAKE, '(Neutered|Spayed).*', 'O')
    , '(Intact).*', 'X')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 04. 오랜 기간 보호한 동물(2)
-- Oracle
SELECT *
FROM (SELECT I.ANIMAL_ID, I.NAME
      FROM ANIMAL_INS I, ANIMAL_OUTS O
      WHERE I.ANIMAL_ID = O.ANIMAL_ID
      AND I.ANIMAL_ID IN O.ANIMAL_ID
      ORDER BY O.DATETIME - I.DATETIME DESC)
WHERE ROWNUM <= 2;

-- MySQL
SELECT ANIMAL_ID, I.NAME
FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
USING (ANIMAL_ID)
ORDER BY (O.DATETIME - I.DATETIME) DESC
LIMIT 2;

-- 05. DATETIME에서 DATE로 형 변환
-- Oracle
SELECT ANIMAL_ID, NAME, TO_CHAR(DATETIME, 'YYYY-MM-DD')
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- MySQL
SELECT ANIMAL_ID, NAME, SUBSTR(DATETIME, 1, 10)
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
