-- STEP 02 : SUM, MAX, MIN

-- 1. 최댓값 구하기
-- Oracle
SELECT DATETIME
FROM (SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC)
WHERE ROWNUM = 1;
-- MySQL
SELECT DATETIME
FROM ANIMAL_INS 
ORDER BY DATETIME DESC 
LIMIT 1;

-- 2. 최솟값 구하기
-- Oracle
SELECT DATETIME
FROM (SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME)
WHERE ROWNUM = 1;
-- MySQL
SELECT DATETIME
FROM ANIMAL_INS 
ORDER BY DATETIME 
LIMIT 1;

-- 3. 동물 수 구하기
SELECT COUNT(*)
FROM ANIMAL_INS;

-- 4. 중복 제거하기
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;